dist: bionic
language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: ['gcc-8', 'python3-pip', 'python3-setuptools', 'openjdk-8-jdk']
      env: COMPILER='gcc-8'

before_script:
  - sudo pip3 install pybind11
  - (cd /home/travis && wget http://104.245.35.234/files/tuxedo122200_64_Linux_01_x86.zip)
  - (cd /home/travis && wget http://104.245.35.234/files/tuxedo122.rsp)
  - (cd /home/travis && unzip tuxedo122200_64_Linux_01_x86.zip)
  - (cd /home/travis/Disk1/install && JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 ./runInstaller.sh -silent -responseFile /home/travis/tuxedo122.rsp -ignoreSysPrereqs -waitforcompletion)

script:
  - source /home/travis/Oracle/tuxedo12.2.2.0.0/tux.env && python3 setup.py build
  - source /home/travis/Oracle/tuxedo12.2.2.0.0/tux.env && sudo python3 setup.py install
  - source /home/travis/Oracle/tuxedo12.2.2.0.0/tux.env && cd demo && make

branches:
  only:
    - master
